spring:
  datasource:
    # docker 连接宿主机 host.docker.internal
    url: jdbc:mysql://localhost:3306/start-project?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: localhost:8611
management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 86400
  password:
  clusterNodes: