host: localhost
spring:
  datasource:
    # docker 连接宿主机 host.docker.internal
    url: jdbc:mysql://${host}:3306/start-project?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 6000
    cluster:
      max-redirects: 3 # 获取失败 最大重定向次数
      nodes:
        - 192.168.199.141:7001
        - 192.168.199.141:7002
        - 192.168.199.141:7003
        - 192.168.199.141:7004
        - 192.168.199.141:7005
        - 192.168.199.141:7006
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  boot:
    admin:
      client:
        url: http://${host}:8611
        instance:
          service-base-url: http://${host}:7070
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always