server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /

spring:
  application:
    name: start-project
  profiles:
    active: @profileActive@
  mvc:
    throw-exception-if-no-handler-found:
      true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: MyHikariCP
      minimum-idle: 5
      idle-timeout: 60000
      maximum-pool-size: 20
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.halink.scaffold.config.mybatisenumhandler.AutoConversionHandler
    map-underscore-to-camel-case: true